const CallApi=[
{
    id: "1",
    image:require('../../assets/img/girl1.png'),
    title:"Muskan",
    time:'yesterday',
    call:'in',
},
{
    id: "2",
    image:require('../../assets/img/my1.jpg'),
        title:"Mohit",
    time:'yesterday',
    call:'out',
},
{
    id: "3",
    image:require('../../assets/img/my.jpg'),
        title:"Panakj RBCP",
    time:'yesterday',
    call:'in',
},
{
    id: "4",
    image:require('../../assets/img/my3.jpg'),
        title:"Prafull ",
    time:'yesterday',
    call:'out',
},
{
    id: "5",
    image:require('../../assets/img/my2.jpg'),
    title:"Pranay Saxena",
    time:'yesterday',
    call:'in',
},
{
    id: "6",
    image:require('../../assets/img/my.jpg'),
        title:"Anuj",
    time:'yesterday',
    call:'in',
},
{
    id: "7",
    image:require('../../assets/img/Sonam.png'),
    title:"Anshika",
    time:'yesterday',
    call:'out',
},
{
    id: "8",
    image:require('../../assets/img/my1.jpg'),
    title:"Subham",
    time:'yesterday',
    call:'in',
},
{
    id: "9",
    image:require('../../assets/img/girlCartoon.jpg'),
    title:"Nidhi Singh",
    time:'yesterday',
    call:'in',
},
{
    id: "10",
    image:require('../../assets/img/girl1.png'),
    title:"Muskan",
    time:'yesterday',
    call:'out',
},
{
    id: "11",
    image:require('../../assets/img/girl1.png'),
    title:"Muskan",
    time:'yesterday',
    call:'in',
},
]
export default CallApi; 