const ChatApi=[  
    {
        id: "1",
        image:require('../../assets/img/girl1.png'),
        title:"Muskan",
        lastMsg:"kha ho",
        time:'yesterday',
        noOfMsg:'2',
},
    {
        id: "2",
        image:require('../../assets/img/my.jpg'),
        title:"Panakj RBCP",
        lastMsg:"Yrr",
        time:'6:25 am ',
        noOfMsg:'5',
},
    {
        id: "3",
        image:require('../../assets/img/my1.jpg'),
        title:"Mohit",
        lastMsg:"ok bhiya",
        time:'6:55 am ',
        noOfMsg:'1',
},
    {
        id: "4",
        image:require('../../assets/img/my2.jpg'),
        title:"Pranay Saxena",
        lastMsg:"bilkul nhi",
        time:'7:14 am ',
        noOfMsg:'10',
},
    {
        id: "5",
        image:require('../../assets/img/my3.jpg'),
        title:"Prafull ",
        lastMsg:"Call kr",
        time:'7:34 am',
        noOfMsg:'0',
},
    {
        id: "6",
        image:require('../../assets/img/Sonam.png'),
        title:"Anshika",
        lastMsg:"good morning",
        time:'8:18 am',
        noOfMsg:'2',
},
    {
        id: "7",
        image:require('../../assets/img/my.jpg'),
        title:"Anuj",
        lastMsg:"Fill this form",
        time:'9:05 am',
        noOfMsg:'4',
},
    {
        id: "8",
        image:require('../../assets/img/girlCartoon.jpg'),
        title:"Nidhi Singh",
        lastMsg:"Assignment ho gya",
        time:'10:00 am',
        noOfMsg:'3',
},
    {
        id: "9",
        image:require('../../assets/img/my1.jpg'),
        title:"Subham",
        lastMsg:"Bhai kuch pise de de",
        time:'10:20 am',
        noOfMsg:'7',
},
    {
        id: "10",
        image:require('../../assets/img/my3.jpg'),
        title:"Divyanshu",
        lastMsg:"Station pr aa",
        time:'1:18 pm ',
        noOfMsg:'1',
},  {
    id: "11",
    image:require('../../assets/img/my3.jpg'),
    title:"Prafull ",
    lastMsg:"Call kr",
    time:'7:34 am',
    noOfMsg:'0',
},
{
    id: "12",
    image:require('../../assets/img/Sonam.png'),
    title:"Anshika",
    lastMsg:"good morning",
    time:'8:18 am',
    noOfMsg:'2',
},
{
    id: "13",
    image:require('../../assets/img/my.jpg'),
    title:"Anuj",
    lastMsg:"Fill this form",
    time:'9:05 am',
    noOfMsg:'4',
},
{
    id: "14",
    image:require('../../assets/img/girlCartoon.jpg'),
    title:"Nidhi Singh",
    lastMsg:"Assignment ho gya",
    time:'10:00 am',
    noOfMsg:'3',
},
{
    id: "15",
    image:require('../../assets/img/my1.jpg'),
    title:"Subham",
    lastMsg:"Bhai kuch pise de de",
    time:'10:20 am',
    noOfMsg:'7',
},
{
    id: "16",
    image:require('../../assets/img/my3.jpg'),
    title:"Divyanshu",
    lastMsg:"Station pr aa",
    time:'1:18 pm ',
    noOfMsg:'1',
},
    
]
export default ChatApi;